apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: clever-cicada-dotnet-basic
  janus-idp.io/tekton: clever-cicada-dotnet-basic
  backstage.io/kubernetes-id: clever-cicada-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: clever-cicada-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
